version: '3'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=java_vulnerability_hub
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=jdbc:mysql://db:3306/java_vulnerability_hub?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      - MYSQL_PORT=3306
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    depends_on:
      - db
