spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html
    encoding: utf-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: myuser
    password: mypassword
    url: jdbc:mysql://db:3306/java_vulnerability_hub?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    throw-exception-if-no-handler-found: true




upload:
  file:
    path: ${user.dir}/upload/
    allowed-types: jpg,png

security:
  referer:
    allow: http://61.171.103.109:8081/,http://127.0.0.1:8081/,http://localhost:8081/

springfox:
  documentation:
    swagger-ui:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
